=== Toscanello/XMLProjekat/Schemes and documents/DigitalCert.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.vakcinisoni.com/DigitalCert"
    xmlns:vx="http://www.vakcinisoni.com/DigitalCert">
    <xs:element name="PCRTest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="testInfo" type="vx:TTest"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="AntigenTest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="testInfo" type="vx:TTest"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="ProteinTest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="testInfo" type="vx:TTest"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType abstract="false" name="TTest">
        <xs:sequence>
            <xs:element name="sampleType" type="xs:string"/>
            <xs:element name="testManufacturer" type="xs:string"/>
            <xs:element name="sampleDate" type="xs:date"/>
            <xs:element name="resultDate" type="xs:date"/>
            <xs:element name="result" type="xs:boolean"/>
            <xs:element name="laboratory" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="certificate">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id" type="xs:long"/>
                <xs:element name="fullName" type="xs:string"/>
                <xs:element name="gender">
                    <xs:simpleType>
                        <xs:restriction base="xs:int">
                            <xs:minInclusive value="0"/>
                            <xs:maxInclusive value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="dateOfBirth" type="xs:date"/>
                <xs:element name="jmbg">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="\d{13}"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="passportNum" type="xs:string"/>
                <xs:element name="vaccination">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="dose" type="vx:TDose" maxOccurs="4" minOccurs="0"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element minOccurs="0" ref="vx:PCRTest"/>
                <xs:element minOccurs="0" ref="vx:AntigenTest"/>
                <xs:element minOccurs="0" ref="vx:ProteinTest"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TDose">
        <xs:sequence>
            <xs:element name="type" type="xs:string"/>
            <xs:element name="manufacturer" type="xs:string"/>
            <xs:element name="batch" type="xs:long"/>
            <xs:element name="date" type="xs:date"/>
            <xs:element name="institution" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="count"/>
    </xs:complexType>
</xs:schema>

=== Toscanello/XMLProjekat/vakcinisoni/data/DigitalCert.xml
<?xml version="1.0" encoding="UTF-8"?>
<certificate xmlns="http://www.vakcinisoni.com"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.vakcinisoni.com/DigitalCert DigitalCert.xsd"
    xmlns:pred="http://www.vakcinisoni.com/rdf/predicate"
    about="http://www.vakcinisoni.com/DigitalCert/2509999880166"
    dateTime="2022-01-05T17:55:55">
    <id>1</id>
    <qrCode>http://www.vakcinisoni.com/DigitalCert/2509999880166</qrCode>
    <fullName property="pred:fullName">Pera Peric</fullName>
    <gender>0</gender>
    <dateOfBirth>1999-08-07</dateOfBirth>
    <jmbg property="pred:jmbg">0708999850006</jmbg>
    <passportNum>00112233</passportNum>
    <vaccination>
        <dose count="1">
            <type>Pfizer</type>
            <manufacturer>BIONTECH MANUFACTURING</manufacturer>
            <batch>2245</batch>
            <date>2021-11-06</date>
            <institution>DZ Ruma</institution>
        </dose>
    </vaccination>
    <PCRTest>
        <testInfo>
            <sampleType>iz nosa</sampleType>
            <testManufacturer>Mitrovcani</testManufacturer>
            <sampleDate>2021-12-07</sampleDate>
            <resultDate>2021-12-07</resultDate>
            <result>false</result>
            <laboratory>Bela ruza</laboratory>
        </testInfo>
    </PCRTest>
</certificate>

=== Toscanello/XMLProjekat/Schemes and documents/DigitalCert.xml
<?xml version="1.0" encoding="UTF-8"?>
<certificate xmlns="http://www.vakcinisoni.com/DigitalCert"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.vakcinisoni.com/DigitalCert DigitalCert.xsd">
    <id>1</id>
    <fullName>Pera Peric</fullName>
    <gender>0</gender>
    <dateOfBirth>2021-12-07</dateOfBirth>
    <jmbg>2509999880166</jmbg>
    <passportNum>00112233</passportNum>
    <vaccination>
        <dose count="1">
            <type>Pfizer</type>
            <manufacturer>BIONTECH MANUFACTURING</manufacturer>
            <batch>2245</batch>
            <date>2021-11-06</date>
            <institution>DZ Ruma</institution>
        </dose>
    </vaccination>
    <PCRTest>
        <testInfo>
            <sampleType>iz nosa</sampleType>
            <testManufacturer>Mitrovcani</testManufacturer>
            <sampleDate>2021-12-07</sampleDate>
            <resultDate>2021-12-07</resultDate>
            <result>false</result>
            <laboratory>Bela ruza</laboratory>
        </testInfo>
    </PCRTest>
</certificate>
