=== Toscanello/XMLProjekat/Schemes and documents/DigitalCertRequest.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.vakcinisoni.com/DigitalCertRequest"
    xmlns:vx="http://www.vakcinisoni.com/DigitalCertRequest">
    <xs:element name="certificateRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="fullName">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute fixed="pred:fullName" name="property"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="birthDate" type="xs:date"/>
                <xs:element name="gender">
                    <xs:simpleType>
                        <xs:restriction base="xs:int">
                            <xs:minInclusive value="0"/>
                            <xs:maxInclusive value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="jmbg">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute fixed="pred:jmbg" name="property"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="passportNum" type="xs:string"/>
                <xs:element name="reason" type="xs:string"/>
                <xs:element name="place">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute fixed="pred:place" name="property"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="requestDate" type="xs:date"/>
            </xs:sequence>
            <xs:attribute name="about" type="xs:string"/>
            <xs:attribute name="dateTime" type="xs:string"/>
            <xs:attribute name="accepted" type="xs:boolean"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Toscanello/XMLProjekat/vakcinisoni/data/DigitalCertificateRequest.xml
<?xml version="1.0" encoding="UTF-8"?>
<certificateRequest xmlns="http://www.vakcinisoni.com"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.vakcinisoni.com/DigitalCertRequest DigitalCertRequest.xsd"
    xmlns:pred="http://www.vakcinisoni.com/rdf/predicate"
    about="http://www.vakcinisoni.com/DigitalCertRequest/1"
    dateTime="2022-01-05T17:55:55"
    accepted="true"
    >
    <fullName property="pred:fullName">Filip Volaric</fullName>
    <birthDate>1999-09-25</birthDate>
    <gender>0</gender>
    <jmbg property="pred:jmbg">2509999880166</jmbg>
    <passportNum>00112233</passportNum>
    <reason>I want to travel</reason>
    <place property="pred:place">Ruma</place>
    <requestDate>2021-12-05</requestDate>
</certificateRequest>
