=== Toscanello/XMLProjekat/Schemes and documents/ImmunizationAccordance.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.vakcinisoni.com/ImmunizationAccordance"
    xmlns:vx="http://www.vakcinisoni.com/ImmunizationAccordance">

    <xs:element name="accordance">
        <xs:complexType>
            <xs:sequence>
                <xs:choice>
                    <xs:element name="jmbg">
                        <xs:complexType>
                            <xs:simpleContent>
                                <xs:extension base="xs:string">
                                    <xs:attribute fixed="pred:jmbg" name="property"/>
                                </xs:extension>
                            </xs:simpleContent>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="foreignCitizenship" nillable="true" type="vx:citizenship"
                        minOccurs="1"/>
                </xs:choice>
                <xs:element name="surname">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute fixed="pred:surname" name="property"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="name">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute fixed="pred:name" name="property"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="parentName" type="xs:string"/>
                <xs:element name="gender">
                    <xs:simpleType>
                        <xs:restriction base="xs:int">
                            <xs:minInclusive value="0"/>
                            <xs:maxInclusive value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="birthDate" type="xs:date"/>
                <xs:element name="birthPlace" type="xs:string"/>
                <xs:element name="address" type="xs:string"/>
                <xs:element name="post" type="xs:string"/>
                <xs:element name="city">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute fixed="pred:city" name="property"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="homeNumber" type="xs:string"/>
                <xs:element name="phoneNum" type="xs:string"/>
                <xs:element name="email" type="xs:string"/>
                <xs:element name="workStatus">
                    <xs:simpleType>
                        <xs:restriction base="xs:int">
                            <xs:minInclusive value="0"/>
                            <xs:maxInclusive value="5"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="employedAt">
                    <xs:simpleType>
                        <xs:restriction base="xs:int">
                            <xs:minInclusive value="0"/>
                            <xs:maxInclusive value="5"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="socialSecurity" type="xs:boolean"> </xs:element>
                <xs:element name="residenceName" type="xs:string"/>
                <xs:element name="isAccordant" type="xs:boolean"/>
                <xs:element name="medicineName" type="xs:string"/>
                <xs:element name="date" type="xs:date"/>
                <xs:element name="vaccineEvidence">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="institution">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute fixed="pred:institution" name="property"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="vaccinationNum" type="xs:string"/>
                            <xs:element name="doctorInfo">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="fullName" type="xs:string"/>
                                        <xs:element name="fax" type="xs:string"/>
                                        <xs:element name="phoneNum" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="table">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="4" name="row">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="vaccineName" type="xs:string"/>
                                                  <xs:element name="dateIssued" type="xs:date"/>
                                                  <xs:element name="issueMethod">
                                                  <xs:simpleType>
                                                  <xs:restriction base="xs:int">
                                                  <xs:minInclusive value="0"/>
                                                  <xs:maxInclusive value="5"/>
                                                  </xs:restriction>
                                                  </xs:simpleType>
                                                  </xs:element>
                                                  <xs:element name="bodyPart">
                                                  <xs:simpleType>
                                                  <xs:restriction base="xs:int">
                                                  <xs:minInclusive value="0"/>
                                                  <xs:maxInclusive value="5"/>
                                                  </xs:restriction>
                                                  </xs:simpleType>
                                                  </xs:element>
                                                  <xs:element name="batch" type="xs:int"/>
                                                  <xs:element name="manufacturer" type="xs:string"/>
                                                  <xs:element name="reaction" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="contraindications" nillable="true"
                                            minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element name="diagnosis" type="xs:string"/>
                                                  <xs:element name="date" type="xs:date"/>
                                                  <xs:element default="false" name="permanent"
                                                  type="xs:boolean"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="about" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="citizenship">
        <xs:sequence>
            <xs:element name="country" type="xs:string"/>
            <xs:element name="passportNum" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== Toscanello/XMLProjekat/vakcinisoni/data/ImmunizationAccordance.xml
<?xml version="1.0" encoding="UTF-8"?>
<accordance xmlns="http://www.vakcinisoni.com"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.vakcinisoni.com ImmunizationAccordance.xsd">
    <jmbg>2509999880166</jmbg>
    <surname>Peric</surname>
    <name>Pera</name>
    <parentName>Petar</parentName>
    <gender>0</gender>
    <birthDate>1999-08-07</birthDate>
    <birthPlace>Sremska Mitrovica</birthPlace>
    <address>Perina 17</address>
    <post>Jalija</post>
    <city>Sremska Mitrovica</city>
    <homeNumber>022 420420</homeNumber>
    <phoneNum>0642042042</phoneNum>
    <email>peraperic@gmail.com</email>
    <workStatus>1</workStatus>
    <employedAt>5</employedAt>
    <socialSecurity>true</socialSecurity>
    <residenceName>Perina Ustanova</residenceName>
    <isAccordant>true</isAccordant>
    <medicineName>Pfizer</medicineName>
    <date>2021-12-07</date>
    <vaccineEvidence>
        <institution>DZ SM</institution>
        <vaccinationNum>1100</vaccinationNum>
        <doctorInfo>
            <fullName>Mika Mikic</fullName>
            <fax>12312312321</fax>
            <phoneNum>022 464 373</phoneNum>
        </doctorInfo>
        <table>
            <row>
                <vaccineName>Kinez</vaccineName>
                <dateIssued>2021-11-05</dateIssued>
                <issueMethod>0</issueMethod>
                <bodyPart>0</bodyPart>
                <batch>11111</batch>
                <manufacturer>BIOTECH</manufacturer>
                <reaction></reaction>
            </row>
            <row>
                <vaccineName>Pfizer</vaccineName>
                <dateIssued>2021-12-05</dateIssued>
                <issueMethod>0</issueMethod>
                <bodyPart>1</bodyPart>
                <batch>12221</batch>
                <manufacturer>BIOTECH</manufacturer>
                <reaction></reaction>
            </row>
            <contraindications>
                <diagnosis>Ima temperaturu</diagnosis>
                <date>2021-11-06</date>
                <permanent>false</permanent>
            </contraindications>
        </table>
    </vaccineEvidence>
</accordance>
