=== Toscanello/XMLProjekat/Schemes and documents/ImmunizationReport.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.vakcinisoni.com/ImmunizationReport"
    xmlns:vx="http://www.vakcinisoni.com/ImmunizationReport">

    <xs:element name="immunizationReport">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="startDate">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:date">
                                <xs:attribute fixed="pred:startDate" name="property"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="finishDate">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:date">
                                <xs:attribute fixed="pred:finishDate" name="property"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="immunizationRequests">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:positiveInteger">
                                <xs:attribute fixed="pred:immunizationRequests" name="property"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="certificateRequests">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:positiveInteger">
                                <xs:attribute fixed="pred:certificateRequests" name="property"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="certificatesIssued">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:positiveInteger">
                                <xs:attribute fixed="pred:certificatesIssued" name="property"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="vaccinesTaken">
                    <xs:simpleType>
                        <xs:restriction base="xs:int">
                            <xs:minInclusive value="0"/>
                            <xs:maxInclusive value="2147483647"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="firstTimeVaccineTaken">
                    <xs:simpleType>
                        <xs:restriction base="xs:int">
                            <xs:minInclusive value="0"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="manufacturers">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" minOccurs="1" name="manufacturer"
                                type="vx:manufacturer"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="reportDate" type="xs:date"/>
            </xs:sequence>
            <xs:attribute name="about" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="manufacturer">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="numberOfVaccines">
                <xs:simpleType>
                    <xs:restriction base="xs:int">
                        <xs:minInclusive value="0"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== Toscanello/XMLProjekat/vakcinisoni/data/ImmunizationReport.xml
<?xml version="1.0" encoding="UTF-8"?>
<immunizationReport xmlns="http://www.vakcinisoni.com"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.vakcinisoni.com ImmunizationReport.xsd">
    <startDate>2021-12-01</startDate>
    <finishDate>2021-12-31</finishDate>
    <immunizationRequests>2758</immunizationRequests>
    <certificateRequests>453</certificateRequests>
    <certificatesIssued>428</certificatesIssued>
    <vaccinesTaken>3225</vaccinesTaken>
    <firstTimeVaccineTaken>1789</firstTimeVaccineTaken>
    <manufacturers>
        <manufacturer>
            <name>Pfizer BioNTech</name>
            <numberOfVaccines>1625</numberOfVaccines>
        </manufacturer>
        <manufacturer>
            <name>Sinopharm</name>
            <numberOfVaccines>1100</numberOfVaccines>
        </manufacturer>
        <manufacturer>
            <name>Sputnik V</name>
            <numberOfVaccines>356</numberOfVaccines>
        </manufacturer>
    </manufacturers>
    <reportDate>2021-12-07</reportDate>
</immunizationReport>
