=== Toscanello/XMLProjekat/Schemes and documents/VaccineCandidate.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.vakcinisoni.com/VaccineCandidate"
    xmlns:vx="http://www.vakcinisoni.com/VaccineCandidate">
    <xs:element name="vaccineCandidate">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="residence">
                    <xs:simpleType>
                        <xs:restriction base="xs:int">
                            <xs:minInclusive value="0"/>
                            <xs:maxInclusive value="2"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="jmbg">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute fixed="pred:jmbg" name="property"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="name">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute fixed="pred:name" name="property"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="surname">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute fixed="pred:surname" name="property"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="email" type="xs:string"> </xs:element>
                <xs:element name="phoneNum">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="[06]\d{6,9}"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="homeNum">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="0\d{8,9}"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="location">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute fixed="pred:location" name="property"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="options">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="manufacturer" type="xs:string" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="isBloodDonor" type="xs:boolean"/>
                <xs:element name="date" type="xs:date"/>
            </xs:sequence>
            <xs:attribute name="about" type="xs:string"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Toscanello/XMLProjekat/vakcinisoni/data/VaccineCandidate.xml
<?xml version="1.0" encoding="UTF-8"?>
<vaccineCandidate xmlns="http://www.vakcinisoni.com"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.vakcinisoni.com/VaccineCandidate VaccineCandidate.xsd"
    xmlns:pred="http://www.vakcinisoni.com/rdf/predicate"
    about="http://www.vakcinisoni.com/VaccineCandidate/1">
    <residence>0</residence>
    <jmbg property="pred:jmbg">2509999880166</jmbg>
    <name property="pred:name">Filip</name>
    <surname property="pred:surname">Volaric</surname>
    <email>filip.kresa@gmail.com</email>
    <phoneNum>0641345948</phoneNum>
    <homeNum>022433857</homeNum>
    <location property="pred:location">Ruma</location>
    <options>
        <manufacturer>Pfizer</manufacturer>
        <manufacturer>Sputnik V</manufacturer>
        <manufacturer>Sinopharm</manufacturer>
        <manufacturer>Astra Zeneca</manufacturer>
        <manufacturer>Moderna</manufacturer>
    </options>
    <isBloodDonor>false</isBloodDonor>
    <date>2021-05-12</date>
</vaccineCandidate>
